# Generated by Django 5.0.4 on 2024-04-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Жильё от застройщика с господдержкой по 2 документам', max_length=100, verbose_name='Название')),
                ('bank_name', models.CharField(default='Сбербанк', max_length=100, verbose_name='Название')),
                ('bank_image', models.ImageField(default='default.png', upload_to='', verbose_name='Логотип банка')),
                ('min_credit_period', models.IntegerField(default=1, null=True, verbose_name='Минимальный срок кредита')),
                ('max_credit_period', models.IntegerField(default=30, null=True, verbose_name='Максимальный срок кредита')),
                ('min_credit_amount', models.IntegerField(default=100000, null=True, verbose_name='Минимальный размер кредита')),
                ('max_credit_amount', models.IntegerField(default=6000000, null=True, verbose_name='Максимальный размер кредита')),
                ('price', models.IntegerField(default='23995', null=True, verbose_name='Платёж')),
                ('percent', models.FloatField(default='7.7', null=True, verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Ипотека',
                'verbose_name_plural': 'Ипотеки',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Описание', max_length=500, null=True, verbose_name='Описание')),
                ('address', models.CharField(default='ул. Ломоносовский проспект, 25к2', max_length=100, null=True, verbose_name='Адрес')),
                ('rooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True, verbose_name='Кол-во комнат')),
                ('price', models.IntegerField(default=25000, null=True, verbose_name='Цена')),
                ('floor', models.CharField(default=1, null=True, verbose_name='Этаж')),
                ('square', models.IntegerField(default=1, null=True, verbose_name='Площадь')),
                ('balcony', models.IntegerField(choices=[(1, 'Балкон'), (2, 'Лоджия')], default=1, null=True, verbose_name='Балкон/лоджия')),
                ('parking', models.IntegerField(choices=[(1, 'Наземная'), (2, 'Подземная')], default=1, null=True, verbose_name='Парковка')),
                ('image', models.ImageField(default='default.jpeg', null=True, upload_to='', verbose_name='Картинка')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендодатель')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_type', models.IntegerField(default=1, verbose_name='Тип недвижимости')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(default='flats/default.png', upload_to='', verbose_name='Картинка')),
                ('price', models.IntegerField(default='Цена', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
