# Generated by Django 5.0.4 on 2024-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ffasdfaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Жильё от застройщика с господдержкой по 2 документам', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'asdfasdf',
                'verbose_name_plural': 'asdfasdf',
            },
        ),
    ]
