# Generated by Django 5.0.4 on 2024-04-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=100, verbose_name='Название')),
                ('description', models.TextField(default='Описание', max_length=500, verbose_name='Описание')),
                ('rooms', models.IntegerField(default=1, verbose_name='Кол-во комнат')),
                ('price', models.IntegerField(default=25000, verbose_name='Цена')),
                ('floor', models.CharField(default=1, verbose_name='Этаж')),
                ('square_general', models.IntegerField(default=34, verbose_name='Площадь общая')),
                ('squere_residential', models.IntegerField(default=18, verbose_name='Площадь жилая')),
                ('squere_kitchen', models.IntegerField(default=6, verbose_name='Площадь жилая')),
                ('balcony', models.IntegerField(choices=[(1, 'Балкон'), (2, 'Лоджия')], default=1, verbose_name='Балкон/лоджия')),
                ('parking', models.IntegerField(choices=[(1, 'Наземная'), (2, 'Подземная')], default=1, verbose_name='Парковка')),
                ('image', models.ImageField(default='flats/default.png', upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
