# Generated by Django 5.0.4 on 2024-04-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ffasdfaf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='price',
            new_name='price_min',
        ),
    ]
