# Generated by Django 5.0.4 on 2024-04-12 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название', max_length=100, verbose_name='Название')),
                ('metro', models.CharField(max_length=50)),
                ('image', models.ImageField(default='flats/default.png', upload_to='', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Минимальная цена квартир')),
                ('mortgage', models.FloatField(verbose_name='Минимальный процент ипотеки')),
                ('flats', models.ManyToManyField(to='app.flat', verbose_name='Квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty_type', models.IntegerField(default=1, verbose_name='Тип недвижимости')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(default='flats/default.png', upload_to='', verbose_name='Картинка')),
                ('price', models.IntegerField(default='Цена', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
