# Generated by Django 5.0.4 on 2024-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_building_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Новостройка', 'verbose_name_plural': 'Новостройки'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='flats',
        ),
    ]
