# Generated by Django 5.0.4 on 2024-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_flat_address_flat_metro_flat_renter_alter_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(default='Адрес', max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='balcony',
            field=models.IntegerField(choices=[(1, 'Балкон'), (2, 'Лоджия')], default=1, null=True, verbose_name='Балкон/лоджия'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(default='Описание', max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(default=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='image',
            field=models.ImageField(default='flats/default.png', null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='metro',
            field=models.CharField(default='Люберцы', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(default='Название', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='parking',
            field=models.IntegerField(choices=[(1, 'Наземная'), (2, 'Подземная')], default=1, null=True, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(default=25000, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.IntegerField(default=1, null=True, verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square_general',
            field=models.IntegerField(default=34, null=True, verbose_name='Площадь общая'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='squere_kitchen',
            field=models.IntegerField(default=6, null=True, verbose_name='Площадь жилая'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='squere_residential',
            field=models.IntegerField(default=18, null=True, verbose_name='Площадь жилая'),
        ),
    ]
