# Generated by Django 5.0.4 on 2024-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_flat_address_alter_flat_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(default='ул. Ломоносовский проспект, 25к2', max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='image',
            field=models.ImageField(default='flats/default.jpeg', null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True, verbose_name='Кол-во комнат'),
        ),
    ]
