# Generated by Django 5.0.4 on 2024-04-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_price_mortgage_price_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='price_min',
            new_name='price',
        ),
    ]
