# Generated by Django 5.0.4 on 2024-05-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_deal_date_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
