# Generated by Django 5.0.4 on 2024-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_renter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(default='Описание', null=True, verbose_name='Описание'),
        ),
    ]
